### PR TITLE
Arg Change

### PR DESCRIPTION
**Pull request by pet1330**
Changed the args to allow a dynamic number of detections to be run simultaneously

### CODE REVIEW

**Comment by marc-hanheide** [comment]
but libgls is still missing, isn't it?

**Comment by marc-hanheide** [comment]
yep, it still is missing, see https://lcas.lincoln.ac.uk/jenkins/job/pr-indigo-circle_detection/2/console

**Comment by marc-hanheide** [comment]
retest this please

**Comment by marc-hanheide** [comment]
github is still having DDoS issues, so I triggered a re-check

**Comment by pet1330** [comment]
retest this please

**Comment by pet1330** [comment]
Solved, the make install needed a doc directory, which was ignored by git as it was empty.

**Pull request merged**
